package com.xmrbi.warehouse.component.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xmrbi.warehouse.data.entity.deliver.RfidSearchHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RFID_SEARCH_HISTORY".
*/
public class RfidSearchHistoryDao extends AbstractDao<RfidSearchHistory, Void> {

    public static final String TABLENAME = "RFID_SEARCH_HISTORY";

    /**
     * Properties of entity RfidSearchHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Content = new Property(0, String.class, "content", false, "CONTENT");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
    }


    public RfidSearchHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public RfidSearchHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RFID_SEARCH_HISTORY\" (" + //
                "\"CONTENT\" TEXT," + // 0: content
                "\"TYPE\" INTEGER NOT NULL );"); // 1: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RFID_SEARCH_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RfidSearchHistory entity) {
        stmt.clearBindings();
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(1, content);
        }
        stmt.bindLong(2, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RfidSearchHistory entity) {
        stmt.clearBindings();
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(1, content);
        }
        stmt.bindLong(2, entity.getType());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public RfidSearchHistory readEntity(Cursor cursor, int offset) {
        RfidSearchHistory entity = new RfidSearchHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // content
            cursor.getInt(offset + 1) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RfidSearchHistory entity, int offset) {
        entity.setContent(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(RfidSearchHistory entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(RfidSearchHistory entity) {
        return null;
    }

    @Override
    public boolean hasKey(RfidSearchHistory entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
